In [2]:
import numpy as np

In [6]:
my_array = np.array([1,10,-5,20])
my_array

array([ 1, 10, -5, 20])

In [9]:
print(f"The mean is {my_array.mean()}")
print(f"The mean is {my_array.std()}")

The mean is 6.5
The mean is 9.447221813845593


In [11]:
print(f"Multiplication by 2: {my_array*2}")

Multiplication by 2: [  2  20 -10  40]


In [14]:
my_array_2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
my_array_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
my_array_2*4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [20]:
print(f"Inverted matrix: \n{my_array_2.T}")

Inverted matrix: 
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [24]:
print(f"Elements in this matrix: {my_array_2.size}")
print(f"Shape of this matrix: {my_array_2.shape}")

Elements in this matrix: 12
Shape of this matrix: (4, 3)


In [30]:
random_integers = np.random.randint(100,200,20)
random_integers

array([185, 102, 121, 114, 183, 182, 161, 111, 168, 126, 175, 134, 178,
       131, 101, 147, 183, 185, 104, 182])

In [34]:
even_numbers = random_integers[random_integers%2==0]
even_numbers

array([102, 114, 182, 168, 126, 134, 178, 104, 182])

In [38]:
sliced_numbers = even_numbers[2:8]
sliced_numbers

array([182, 168, 126, 134, 178, 104])

In [44]:
arr1 = np.random.randint(0,10,4)
arr2 = np.random.randint(0,10,4)

print(f"The two arrays are: \n{arr1} \n{arr2}")

The two arrays are: 
[1 0 4 2] 
[5 6 0 2]


In [49]:
print(f"The sum of the two arrays is {arr1 + arr2}")
print(f"The difference of the two arrays is {arr1 - arr2}")
print(f"The multiplication of the two arrays is {arr1 * arr2}")

The sum of the two arrays is [6 6 4 4]
The difference of the two arrays is [-4 -6  4  0]
The multiplication of the two arrays is [5 0 0 4]


In [52]:
np.dot(arr1, arr2) # The resut is the sum of the values calculated from the multiplication of the two arrays

np.int64(9)

In [55]:
(arr1*arr2).sum()

np.int64(9)